/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import javax.swing.JOptionPane;

/**
 *
 * @author franc
 */
public class SportSelection extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SportSelection.class.getName());

    /**
     * Creates new form SportSelection
     */
    public SportSelection() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tabSelection = new javax.swing.JPanel();
        Ball = new javax.swing.JButton();
        Board = new javax.swing.JButton();
        Racket = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Select Sport");
        setAlwaysOnTop(true);
        setResizable(false);

        jLabel1.setText("Select Your Sport");

        Ball.setText("Ball");
        Ball.addActionListener(this::BallActionPerformed);

        Board.setText("Board");
        Board.addActionListener(this::BoardActionPerformed);

        Racket.setText("Racket");
        Racket.addActionListener(this::RacketActionPerformed);

        javax.swing.GroupLayout tabSelectionLayout = new javax.swing.GroupLayout(tabSelection);
        tabSelection.setLayout(tabSelectionLayout);
        tabSelectionLayout.setHorizontalGroup(
            tabSelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabSelectionLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(Ball)
                .addGap(28, 28, 28)
                .addComponent(Board)
                .addGap(27, 27, 27)
                .addComponent(Racket)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        tabSelectionLayout.setVerticalGroup(
            tabSelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabSelectionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabSelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ball)
                    .addComponent(Board)
                    .addComponent(Racket))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabSelection, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tabSelection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BallActionPerformed
        JOptionPane.showMessageDialog(this, "Ball sports are not available yet.",
        "Unavailable", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_BallActionPerformed

    private void BoardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoardActionPerformed
        JOptionPane.showMessageDialog(this, "Board sports are not available yet.",
        "Unavailable", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_BoardActionPerformed

    private void RacketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RacketActionPerformed
        new ModeSelection().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_RacketActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SportSelection().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Ball;
    private javax.swing.JButton Board;
    private javax.swing.JButton Racket;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel tabSelection;
    // End of variables declaration//GEN-END:variables
}
